Repository meta-pytorch/LeanRL, pull requests merged in 2024-09, with the labels that each got.

#1 [Doc] Minor documentation fix
  README.md
  pyproject.toml
Labels: bug, documentation, CLA Signed

#4 [BugFix] Fix installation instructions
  README.md
  leanrl/ppo_atari_envpool_torchcompile.py
  leanrl/ppo_continuous_action_torchcompile.py
  leanrl/sac_continuous_action_torchcompile.py
  leanrl/td3_continuous_action_torchcompile.py
  requirements/requirements-atari.txt
  requirements/requirements-dm_control.txt
  requirements/requirements-docs.txt
  requirements/requirements-envpool.txt
  requirements/requirements-jax.txt
  requirements/requirements-mujoco.txt
  requirements/requirements-optuna.txt
  requirements/requirements-pettingzoo.txt
  requirements/requirements-procgen.txt
  requirements/requirements.txt
Labels: bug, CLA Signed

#6 [Quality] Remove timeit
  leanrl/ppo_atari_envpool_torchcompile.py
Labels: CLA Signed

#7 Update README.md with discord shield
  README.md
Labels: CLA Signed

#8 Change discord shield appearance
  README.md
Labels: CLA Signed
